# Generated by Django 4.2.1 on 2023-05-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_food_delete_choice_delete_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="food",
            name="options",
            field=models.ManyToManyField(to="order.option"),
        ),
    ]
