# Generated by Django 4.2.1 on 2023-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_rename_food_text_food_name_remove_food_pub_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shoppingcart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("remark", models.CharField(max_length=200)),
                ("count", models.DecimalField(decimal_places=0, max_digits=8)),
                ("subtotal", models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name="option",
            name="price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
