# Generated by Django 4.2.1 on 2023-05-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="shopping_cart",),
        migrations.AddField(
            model_name="order",
            name="shopping_cart_items",
            field=models.ManyToManyField(to="order.shoppingcart"),
        ),
    ]
