# Generated by Django 4.2.1 on 2023-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_order_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("remark", models.CharField(max_length=200)),
                ("count", models.DecimalField(decimal_places=0, max_digits=8)),
                ("subtotal", models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.RemoveField(model_name="order", name="shopping_cart_items",),
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.ManyToManyField(to="order.order_item"),
        ),
    ]
